apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "authtokenbroker-chart.name" $ }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /api/health
            pathType: Prefix
            backend:
              service:
                name: {{ include "authtokenbroker-chart.fullname" $ }}
                port:
                  number: 80 
          - path: /WeatherForecast  # New path for the new pod
            pathType: Prefix
            backend:
              service:
                name: "helloworldapi-chart"  # Use the correct service name
                port:
                  number: 80  # Ensure the correct port is specified        
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}

