apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: 4.10.x
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  values:
    controller:
      config:
          proxy-body-size: 100m
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      service:
        externalTrafficPolicy: "Local"
        type: LoadBalancer
      allowSnippetAnnotations: true