apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworldapi-chart.fullname" . }}
  labels:
    {{ include "helloworldapi-chart.labels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "helloworldapi-chart.name" . }}



