apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: 1.14.x
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: jetstack
  values:
    installCRDs: true
    enableCertificateOwnerRef: true
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
    webhook:
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
    cainjector:
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
