# Azure Function Docker Image
image:
  repository: thomascontainerregistry.azurecr.io/hello-world-api
  tag: latest
  pullPolicy: Always

# Kubernetes Service settings
service:
  type: ClusterIP
  port: 443
  targetPort: 443
  protocol: TCP

# Ingress settings
ingress:
  enabled: true
  hosts:
    - host: kubernetes.soulsseeker.com
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - hosts:
        - kubernetes.soulsseeker.com
      secretName: azure-function-tls-2