# Azure Function Docker Image
image:
  repository: thomascontainerregistry.azurecr.io/hello-world-api
  tag: latest
  pullPolicy: Always

# Kubernetes Service settings
service:
  type: ClusterIP
  port: 80
  targetPort: 80
  protocol: TCP
